### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by zulhfreelancer** [vasa-develop/ipfscloud#12]
Hi,

I just finished watching all four videos on your official YouTube channel. This project looks really cool and I'm excited to learn more about this.

I have few questions here:

1. What is the business model behind this project? I mean, how much developers need to pay if we want to use this IPFS Cloud project in our project?

2. Do you have upload widget and API for developers to put in their project? Something like [this](https://www.dropbox.com/developers/saver) and [this](https://developer.box.com/docs/box-content-uploader).

    Use case - I'm planning to build a membership site and I want to let the members to upload files to IPFS Cloud. Would be really nice if you have upload widget that do the magic for us so that we can integrate it faster with less configurations/errors.

    As developer, I'm expecting a callback containing the file hash after the file is successfully uploaded to IPFS. This can be from back-end (IPFS Cloud server) or from the upload widget JavaScript itself.

3. How do you handle access token? From one of your video, seems like there is no token or signature to access uploaded file.

    Use case - I want the uploaded file is only valid for X amount of time i.e. 1 hour. At the same time, I also want only specific people can download the files.

    If there is no token or signature, technically everyone can access the file by using IPFS Gateway.
    
    Possible to have something like this? `ipfs.io/ipfs/HASH/?signature=SIGNATURE-GENERATED-BY-MY-BACK-END-OR-IPFS-CLOUD`

4. What does **Video Streaming** means inside your [roadmap](https://gateway.ipfs.io/ipfs/QmcgCK3eiHAoKgRJoqHsCu8ahkdt2nH1yWnPEAkp36EKkR)? Does it mean I can build decentralized Netflix using this project?

Thank you.

**Comment by vasa-develop** [comment]
Hi @zulhfreelancer 
Thanks for showing interest in this project :)

First a bit background on what it is all about and what are we upto:
 
IpfsCloud and other apps(IpfsDocs, IpfsHost, IpfsCollab and much more coming soon) are projects under **[ClusterLabs](https://clusterlabs.io)**. 
**ClusterLabs is an ecosystem, providing apps, infrastructure and tools enabling decentralization. It aims to bring the Internet 3.0, in a frictionless way to the world.**

* Right now we focussed on creating an open marketplace of storage and computation power. So, essentially we are first creating an **UBER for data and computation power economy**. So, you can rent out unused storage space and computation power(later in roadmap) to other users in the network.

* After that we are going to create **Firebase for Dapps**. A suit for:
  * Decentralized Authentication methods.
  * Scalable Storage and Database integrated with Blockchain. 
* We are also planning to develop a search engine and Decentralized AD network other stuff...but that is not under near future RoadMap.

**The basic motive of ClusterLabs is NOT to introduce a closed environment(like most of today's projects which introduce "utility" coins, which don't have much utility) but instead an open environment  which is actually workable today.**

We aim to build things which developers can start using in everyday development; even in production environments. Thus allowing people to use power of decentralized tech in everday life.

Now, let's answer the questions:

1. Parts of the project will be open-sourced. Like 
  * Open APIs for IpfsCloud, by with you can interact with the above mentioned network.
  * In our decentralized firebase, we will provide some free plans. Paid ones for better features.
As we are not providing the storage/computation power, we will only charge for the service. At this point in time, we haven't decided the exactly on how much we are going to charge.
**If you are interested in collaborating/using IpfsCloud in your project, then you can contact us at vasa@towardsblockchain.com**

2. We do have **[open APIs](https://ipfscloud.store/app/docs/v1)** available for uploading data to IpfsCloud. I will soon introduce a widget script. **I will try to build one this weekend. So, keep an eye on [Developer Docs Page](https://ipfscloud.store/app/docs/v1)**. If you want any other feature in IpfsCloud, then feel free open an issue.

3. I actually made this feature, but abandoned it in between the developement. I will also add this on the **[Developer Docs Page](https://ipfscloud.store/app/docs/v1)** in a week or two.

4. Yes, you could build decentralized NetFlix using the video streaming platform. 
   P.S. the roadmap will be updated soon.

**Comment by vasa-develop** [comment]
Here is the documentation for the widget you taked about in question 2: **[IpfsCloud upload button Widget](https://github.com/vasa-develop/ipfscloud/blob/master/README.md#ipfscloud-upload-button-widget)**
