### ISSUE TITLE
hosting bug

### ISSUE THREAD

**Issue by michel47** [vasa-develop/ipfscloud#16]
The pinning for host's files on IPFS doesn't work anymore

can you propose the option disable it
and have the use take care of the pinning on his own *with a warning message of course*

Thanks
+Michel

**Comment by vasa-develop** [comment]
Sure, I will add the Warning.

Actually we were testing out different providers. Maybe when we were testing it out on production, you added your files, and now the same provider is down. So, that may have caused the above issue.

**Comment by vasa-develop** [comment]
Added the Warning :)
See [here](http://gateway.ipfscloud.store/ipfs/QmU7DPWoUSRWcDA6KnWpwnURAppDLPUSdbARK3y5uHkNFp).
