### ISSUE TITLE
IPFS CLOUD

### ISSUE THREAD

**Issue by kipper68** [vasa-develop/ipfscloud#18]
Hi
I'm new to Git hub  and IPFS Cloud.
Can anyone help. I opened an IPFS cloud  account and started uploading files which appeared in my documents folder. all looked well then suddenly  any new files I added stopped showing in the folder ?
Is there a problem . or am I doing something wrong.
Thanks

**Comment by vasa-develop** [comment]
Right now we don't have the capability to add files to a folder. We are working on a total restructuring of the project to make it more like today's services like Google Drive in terms of features. 
Also, we are adding storage collaboration platform using `ipfs cluster`. 
As you are new to IPFS, I can tell you that we are working to make things better:)
