### ISSUE TITLE
Can't login on Firefox on Linux using Google account

### ISSUE THREAD

**Issue by NatoBoram** [vasa-develop/ipfscloud#2]
I previously created an account using my phone, and now I want to access it on my computer. It works with Chrome, but not with Firefox.

Basically, when I click on "Continue using Google", there's a pop-up that opens then immediately closes.

![image](https://user-images.githubusercontent.com/10495562/47628866-3204ca80-db0e-11e8-95a6-eab2e9cd824d.png)

![image](https://user-images.githubusercontent.com/10495562/47628859-20232780-db0e-11e8-99a0-2b0dd85eeece.png)

**Comment by vasa-develop** [comment]
I can't seem to reproduce it on my system
Evironment used:
Browser(Firefox mozilla): Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
OS: Ubuntu 16.04 LTS

But I have heard the same issue from some other users too.
I will check it out in the environment you mentioned above.

**Comment by vasa-develop** [comment]
@NatoBoram  I just tried logging in to [ipfscloud](https://ipfscloud.store) using the same browser version that you mentioned above. It worked. Seems to issue with the OS version. 
If someone uses Ubuntu 18.10, please check it out that if it is a general issue.

Thanks

**Comment by NatoBoram** [comment]
Oh, I think I found a possible cause.

![image](https://user-images.githubusercontent.com/10495562/47952924-b90dd480-df4c-11e8-8ddc-8ba774de3607.png)

Can you confirm if it works with this specific option?

**Comment by vasa-develop** [comment]
Is it working after allowing the cookies? If yes, then we can close this issue...
