### ISSUE TITLE
How do I change my password?

### ISSUE THREAD

**Issue by NatoBoram** [vasa-develop/ipfscloud#3]
Because of #2, I'm trying to set a password so I can login. However, there's no password field on my profile.

![image](https://user-images.githubusercontent.com/10495562/47628973-ef8fbd80-db0e-11e8-8e2b-c4ac417c23cd.png)

**Comment by vasa-develop** [comment]
My Bad. I forgot to add it. Will add it soon.

**Comment by vasa-develop** [comment]
Added Change Password feature(profile.html) and Forgot password feature(login.html) in the [development branch](https://github.com/vasa-develop/ipfscloud/commit/b7c1fff2149113893e99607bd1b315658288b029).
