### ISSUE TITLE
Use a separate CSS file instead of writing it in a page's head

### ISSUE THREAD

**Issue by NatoBoram** [vasa-develop/ipfscloud#6]
I mean, you can't excuse [that](https://github.com/vasa-develop/ipfscloud/blob/master/private.html#L29).

CSS pages can be cached, saving network data and making web pages download faster.

https://www.w3schools.com/html/html_css.asp

**Comment by vasa-develop** [comment]
Sure. I have to do a lot of changes to the site(most probably shift it to angular or react).
I appreciate your interest in the project.
